# Generated by Django 5.1.4 on 2024-12-10 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Tracking Date')),
                ('notes', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('mushroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mushroom')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
