# Generated by Django 5.1.4 on 2024-12-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushroom',
            old_name='commonName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mushroom',
            old_name='scientificName',
            new_name='scientific',
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
